apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockube-minikube-a
spec:
  selector:
    matchLabels:
      app: dockube-minikube-a
  replicas: 1
  template:
    metadata:
      labels:
        app: dockube-minikube-a
    spec:
      containers:
      - name: dockube-minikube-a
        image: mittalkartik87/dockube:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 90

---

apiVersion: v1
kind: Service
metadata:
  name: dockube-minikube-a
spec:
  type: 
  selector:
    app: dockube-minikube-a
  ports:
    - protocol: "TCP"
      port: 90
      targetPort: 90